version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  bowls-app:
    build: .
    container_name: bowls-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017